/**
 * Persistence for the timetable.
 *
 * PLATFORM layer: this is the only file in the timetable feature that touches
 * chrome.storage. The model (timetable.js) and the mail rules
 * (timetable-mail.js) are pure, so they can be tested without a browser and
 * cannot accidentally depend on storage behaviour.
 *
 * WHY chrome.storage.local AND NOT sync
 * -------------------------------------
 * `storage.sync` has an 8KB per-item quota. A twelve-course timetable with
 * full provenance and history exceeds that within a semester of edits, and
 * the failure mode is a silent write rejection — the user's timetable stops
 * saving and nothing says so. `local` has a 10MB budget. The trade is that
 * the timetable does not follow the user to another machine, which is the
 * honest limitation to accept over a schedule that silently stops persisting.
 *
 * EVERY ENTRY POINT DEGRADES. A storage failure must leave the app usable
 * with an in-memory timetable, never throw into a click handler. This matches
 * the rule the rest of the codebase already follows.
 */

import { emptyState } from './timetable.js';

const KEY = 'timetable';
const SCHEMA = 1;

/**
 * Read the timetable.
 *
 * Never throws and never returns null: a missing, corrupt or future-schema
 * blob all degrade to a fresh empty state, because the alternative is an app
 * that will not open. A corrupt blob is left on disk rather than deleted, so
 * it can be recovered by hand if it ever matters.
 */

/**
 * Is this stored record safe for every consumer to touch?
 *
 * The bar is deliberately "will not throw downstream", not "is complete".
 * A section with no room is a legitimate partial state the document itself
 * produces, and rejecting it would discard real data. A record with no id, or
 * with `meetings` that is not an array, is not a timetable entry at all.
 */
function usableEntry(e) {
  if (!e || typeof e !== 'object') return false;
  if (typeof e.id !== 'string' || !e.id) return false;
  if (typeof e.comCode !== 'string' || !e.comCode) return false;
  if (typeof e.section !== 'string' || !e.section) return false;
  // Every render path iterates these two without guarding them.
  if (!Array.isArray(e.meetings)) return false;
  if (!Array.isArray(e.history)) return false;
  return true;
}

export async function loadTimetable(storage = chrome.storage.local) {
  try {
    const got = await storage.get(KEY);
    const blob = got?.[KEY];
    if (!blob || typeof blob !== 'object') return emptyState();
    if (blob.schemaVersion !== SCHEMA) return emptyState();
    if (!Array.isArray(blob.entries)) return emptyState();
    /*
     * VALIDATE THE ENTRIES, NOT JUST THE ARRAY.
     *
     * Checking `Array.isArray(entries)` and stopping there let a blob holding
     * junk load "successfully" and then throw on the first render -- weekView
     * and detectConflicts both do `e.meetings`, examEvents does `e.midsem`.
     * One bad record made the panel unopenable, which is a total loss where a
     * partial timetable the user can see and repair would do.
     *
     * Unusable records are DROPPED and COUNTED rather than patched up. A
     * repaired-with-defaults entry is a fabricated one: it would claim a class
     * exists with no time and no source, which is exactly the invented data
     * this system refuses to produce. `dropped` gives the UI something honest
     * to say.
     */
    const kept = [];
    let dropped = 0;
    for (const e of blob.entries) {
      if (usableEntry(e)) kept.push(e);
      else dropped += 1;
    }

    return {
      ...emptyState(),
      ...blob,
      entries: kept,
      dropped,
      conflicts: Array.isArray(blob.conflicts) ? blob.conflicts : [],
      appliedMail: Array.isArray(blob.appliedMail) ? blob.appliedMail : [],
    };
  } catch {
    return emptyState();
  }
}

/**
 * Write the timetable.
 *
 * Returns {ok, error} rather than throwing, so every caller has a failure
 * channel it can surface. Returning void here was the exact defect found in
 * views.js: mutators that could fail silently inside async click handlers.
 */
export async function saveTimetable(state, storage = chrome.storage.local) {
  try {
    await storage.set({ [KEY]: { ...state, schemaVersion: SCHEMA } });
    return { ok: true, error: null };
  } catch (err) {
    return { ok: false, error: err?.message || 'could not save the timetable' };
  }
}

/** Remove the timetable entirely. Used by sign-out and by "start over". */
export async function clearTimetable(storage = chrome.storage.local) {
  try {
    await storage.remove(KEY);
    return { ok: true, error: null };
  } catch (err) {
    return { ok: false, error: err?.message || 'could not clear the timetable' };
  }
}

/**
 * Load the shipped source data.
 *
 * Static, generated by tools/parse-timetable.mjs from the official documents.
 * Fetched once and memoised: it is ~600KB of JSON and re-parsing it on every
 * course search would be felt.
 */
let sourceData = null;
let sourcePromise = null;

export function _resetSourceData() {
  sourceData = null;
  sourcePromise = null;
}

export async function loadSourceData(fetcher) {
  if (sourceData) return sourceData;
  if (sourcePromise) return sourcePromise;

  const get = fetcher || (async () => {
    const url = chrome.runtime.getURL('src/timetable/data.json');
    const res = await fetch(url);
    if (!res.ok) throw new Error(`timetable data: HTTP ${res.status}`);
    return res.json();
  });

  sourcePromise = get()
    .then((d) => {
      sourceData = d;
      sourcePromise = null;
      return d;
    })
    .catch((err) => {
      sourcePromise = null;
      // A missing data file is a packaging error, not a user error. Return an
      // empty catalogue so the UI can say "the timetable data did not load"
      // instead of throwing into whatever opened the builder.
      sourceData = { courses: [], changes: [], error: err?.message || 'load failed' };
      return sourceData;
    });
  return sourcePromise;
}

/**
 * Search the course catalogue.
 *
 * Matches course number, title and computer code. Ranked so an exact course
 * number beats a title substring — someone typing "CS F111" wants that course,
 * not every course whose title happens to contain those letters.
 */
export function searchCourses(data, query, limit = 20) {
  const q = String(query || '').trim().toLowerCase();
  if (!q) return [];
  const compact = q.replace(/\s+/g, '');
  const out = [];

  for (const c of data?.courses || []) {
    const no = c.courseNo.toLowerCase();
    const noCompact = no.replace(/\s+/g, '');
    const title = c.title.toLowerCase();

    let score = 0;
    if (noCompact === compact) score = 100;
    else if (noCompact.startsWith(compact)) score = 80;
    else if (c.comCode === q) score = 70;
    else if (title.startsWith(q)) score = 60;
    else if (noCompact.includes(compact)) score = 40;
    else if (title.includes(q)) score = 30;

    if (score) out.push({ course: c, score });
  }

  return out
    .sort((a, b) => b.score - a.score || a.course.courseNo.localeCompare(b.course.courseNo))
    .slice(0, limit)
    .map((x) => x.course);
}

/** Find one course by its computer code, the identity used everywhere. */
export function courseByComCode(data, comCode) {
  return (data?.courses || []).find((c) => c.comCode === comCode) || null;
}
