/**
 * Keyword rules -- stage 2 of classification.
 *
 * ===========================================================================
 * GENERATED FILE -- DO NOT EDIT BY HAND
 * ===========================================================================
 * Source:    CLASSIFICATION_DATA_PACK.md sections 6 and 9
 * Regenerate: node tools/gen-pattern-rules.mjs
 *
 * These values are the ORIGINAL weights from the previous version's
 * `lib/pattern-classifier/rules/*.js`, carried over exactly. An earlier
 * hand-written port rewrote all of them onto a 40/25/15/8 scale and dropped
 * 802 keys while claiming to be a faithful copy. See
 * notes/CLASSIFIER_CORRECTION.md. Generating the file removes the opportunity
 * to make that mistake again.
 *
 * SHAPE
 *   { category, senderExact[], senderContains[], subjectWeights{}, snippetWeights{} }
 *
 * SCORING (data pack section 8)
 *   senderExact hit     -> +80 * 1.5   and sets hasSenderMatch
 *   senderContains hit  -> +55 * 1.5   and sets hasSenderMatch
 *   subject keyword     -> +weight * 1.2, subsequent hits * 0.6
 *   snippet keyword     -> +weight * 1.0, subsequent hits * 0.6
 *
 * All keys are matched case-insensitively against a lowercased haystack.
 *
 * ARRAY ORDER is BUILT_IN_RULES from data pack section 9. Stage 2 takes the
 * highest score rather than the first match, so order does not decide the
 * winner -- but it does decide ties, via resolveConflict.
 */

export const PATTERN_RULES = [
  {
    category: 'external-promotions',
    senderContains: [
      'newsletter',
      'marketing',
      'promo',
      'unsubscribe',
    ],
    subjectWeights: {
      newsletter: 60,
      promotion: 65,
      sale: 55,
      offer: 50,
      discount: 55,
      deal: 45,
      'limited time': 50,
      'special offer': 55,
      exclusive: 40,
      subscribe: 45,
      unsubscribe: 30,
      win: 35,
      free: 30,
    },
    snippetWeights: {
      newsletter: 30,
      promotion: 35,
      sale: 25,
      offer: 25,
      discount: 25,
      unsubscribe: 20,
    },
  },
  {
    category: 'external-services',
    senderContains: [
      'github',
      'openai',
      'anthropic',
      'kaggle',
      'medium',
      'substack',
      'nvidia',
      'huggingface',
    ],
    subjectWeights: {
      notification: 50,
      alert: 45,
      update: 40,
      security: 55,
      account: 45,
      verify: 50,
      password: 55,
      subscription: 45,
      invoice: 50,
      receipt: 50,
      order: 45,
      shipment: 50,
    },
    snippetWeights: {
      notification: 25,
      alert: 20,
      account: 25,
      security: 30,
      verify: 25,
    },
  },
  {
    category: 'internship',
    senderExact: [
      'placement unit',
      'training and placement',
      'tpo',
      'placement office',
    ],
    senderContains: [
      'placement',
      'training-and-placement',
    ],
    subjectWeights: {
      placement: 70,
      'pre-placement': 80,
      ppt: 75,
      'pre-placement talk': 85,
      ppi: 80,
      ppo: 85,
      internship: 65,
      ps1: 60,
      ps2: 60,
      'ps-1': 60,
      'ps-2': 60,
      'summer internship': 80,
      'winter internship': 80,
      recruitment: 60,
      'campus recruitment': 80,
      'job opening': 55,
      'job opportunity': 55,
      'job offer': 60,
      'job alert': 55,
      'job vacancy': 55,
      'job listing': 55,
      'job posting': 55,
      'job fair': 55,
      'job interview': 55,
      'job placement': 60,
      company: 30,
      interview: 40,
      offer: 35,
      dream: 60,
      'super dream': 70,
      'day 1': 60,
      'day 2': 60,
      slot: 40,
      'resume shortlist': 70,
      shortlist: 50,
      hiring: 60,
      apply: 50,
      registration: 45,
      opportunity: 45,
      'industrial training': 60,
      summer: 30,
      winter: 30,
      superset: 70,
      'internship cycle': 70,
    },
    snippetWeights: {
      placement: 40,
      internship: 40,
      recruitment: 35,
      'pre-placement': 45,
      hiring: 35,
      apply: 25,
      'job opening': 30,
      'job opportunity': 30,
      'job offer': 30,
      'job alert': 30,
      opportunity: 25,
      register: 20,
      company: 20,
      'apply now': 25,
    },
  },
  {
    category: 'competitions',
    senderContains: [
      'hackathon',
      'contest',
      'competition',
    ],
    subjectWeights: {
      hackathon: 80,
      hack: 50,
      competition: 60,
      'case competition': 80,
      'case study': 60,
      coding: 55,
      'coding contest': 75,
      'programming contest': 75,
      quiz: 40,
      'quiz competition': 65,
      challenge: 55,
      'tech challenge': 70,
      pitch: 50,
      pitching: 55,
      ideathon: 70,
      ideate: 50,
      hackfest: 80,
      hackweek: 80,
      grid: 60,
      'flipkart grid': 80,
      'optum hackathon': 80,
      'axis moves': 70,
      'axis-case': 70,
      smartprix: 70,
      zerodha: 70,
      rubix: 70,
      'code red': 70,
      aerotrix: 70,
      aerothon: 70,
      enumerate: 70,
      byteverse: 70,
      olympiad: 75,
      'math olympiad': 80,
      'science olympiad': 80,
    },
    snippetWeights: {
      hackathon: 40,
      competition: 30,
      contest: 35,
      register: 15,
      prize: 25,
      participate: 20,
    },
  },
  {
    category: 'clubs',
    senderContains: [
      'club',
      'society',
      'chapter',
      'association',
      'forum',
      'arbits',
      'astro',
      'bitsmun',
      'coding club',
      'comedy hub',
      'comhub',
      'communo',
      'consulting club',
      'bpcc',
      'crac',
      'creative activities',
      'cubing',
      'dance club',
      'debating',
      'embryo',
      'elas',
      'english press',
      'fmac',
      'fashion club',
      'fitbits',
      'gaming club',
      'gdsc',
      'google developer student',
      'gurukul',
      'hindi activities',
      'has.pilani',
      'hindi drama',
      'hdc.pilani',
      'hindi press',
      'hpc.pilani',
      'kalamvansh',
      'karaoke',
      'kc.pilani',
      'mac.pilani',
      'matrix.pilani',
      'media relations',
      'mrc.pilani',
      'mime club',
      'music club',
      'nss.pilani',
      'national service scheme',
      'nirmaan',
      'operations and strategies',
      'parc.pilani',
      'atamnirbhar',
      'photography club',
      'photog',
      'poetry club',
      'postman lab',
      'product management',
      'pm.pilani',
      'public policy club',
      'ppc.pilani',
      'quant club',
      'radioaktiv',
      'renewable energy',
      'sac.pilani',
      'students academic cell',
      'sovesa',
      'spic macay',
      'sarc.pilani',
      'students alumni relations',
      'tedx',
      'eastern outlook',
      'toastmasters',
      'biological association',
      'chemical engineering association',
      'chemistry association',
      'civil engineering association',
      'computer science association',
      'eee association',
      'economics and finance',
      'humanities association',
      'instrumentation forum',
      'manufacturing engineering',
      'mathematics association',
      'mechanical engineering association',
      'pharmacy association',
      'physics association',
      'bits pilani association',
      'andhra samiti',
      'capitol',
      'gurjari',
      'haryana cultural',
      'kairali',
      'udgam',
      'kannada vedike',
      'madhyansh',
      'maharashtra mandal',
      'maurya vihar',
      'moruchhaya',
      'punjab cultural',
      'sangam',
      'tamil mandram',
      'utkal samaj',
      'share.pilani',
      'ifsa',
      'acm.pilani',
      'ieee.pilani',
      'asme',
      'ai-che',
      'ii-che',
      'acm-w',
      'anant',
      'ikr',
      'gravity.pilani',
      'electric.pilani',
      'radio control',
      'robocon',
      'team bits',
      'sally robotics',
      'criss',
      'kxr lab',
      'sutt',
      'cel.pilani',
      'entrepreneurship and leadership',
      'pilani innovation',
      'ieds',
      '180dc',
      'wall street club',
    ],
    subjectWeights: {
      recruitment: 50,
      audition: 60,
      induction: 55,
      meeting: 30,
      'general body': 55,
      club: 40,
      society: 40,
      chapter: 40,
      association: 40,
      sig: 50,
      'student interest group': 60,
      member: 25,
      team: 20,
      'core team': 45,
      event: 15,
      annual: 15,
      workshop: 20,
      session: 15,
      'open house': 40,
      'treasure hunt': 50,
      'hack night': 45,
      'film screening': 45,
      'jam session': 45,
      'open mic': 50,
      concert: 40,
      exhibition: 35,
      competition: 35,
      quiz: 40,
      'coding contest': 45,
      debate: 50,
      'moot court': 50,
      'model un': 55,
      'fashion show': 50,
      'dance performance': 45,
      'music performance': 45,
      'nukkad natak': 55,
      'street play': 50,
      'poster making': 40,
      'photography contest': 45,
      'film making': 45,
      'product management': 50,
      consulting: 40,
      finance: 35,
      'public policy': 50,
      quant: 40,
      toastmasters: 50,
      tedx: 55,
      'ted talk': 55,
      alumni: 35,
      nss: 45,
      nirmaan: 50,
      sovesa: 50,
      'spic macay': 55,
      gurukul: 45,
      kalamvansh: 50,
      embryo: 50,
      communo: 50,
      arbits: 50,
      bitsmun: 55,
      fitbits: 45,
      radioaktiv: 50,
      'andhra samiti': 45,
      gurjari: 45,
      kairali: 45,
      udgam: 45,
      'tamil mandram': 45,
      'maharashtra mandal': 45,
      'punjab cultural': 45,
      'utkal samaj': 45,
      'kannada vedike': 45,
      madhyansh: 45,
      'maurya vihar': 45,
      moruchhaya: 45,
      sangam: 40,
      capitol: 40,
      'haryana cultural': 45,
      acm: 50,
      ieee: 50,
      asme: 50,
      ifsa: 50,
      share: 40,
      'acm-w': 50,
      robocon: 55,
      'sally robotics': 50,
      anant: 45,
      ikr: 45,
      gravity: 40,
      'radio control': 45,
      'kxr lab': 45,
      criss: 40,
      sutt: 40,
      '180dc': 50,
      'wall street club': 55,
      cel: 45,
      entrepreneurship: 45,
      ieds: 50,
    },
    snippetWeights: {
      club: 25,
      society: 25,
      association: 25,
      chapter: 20,
      forum: 20,
      recruitment: 30,
      member: 20,
      join: 20,
      audition: 30,
      induction: 25,
      'general body': 30,
      sig: 25,
      'student interest group': 30,
      'core team': 25,
      event: 15,
      rehearsal: 20,
      practice: 15,
      'annual day': 25,
      fest: 20,
      'open mic': 25,
      concert: 20,
      debate: 25,
      hack: 20,
      coding: 20,
      photography: 20,
      fashion: 20,
      dance: 20,
      music: 20,
      drama: 20,
      poetry: 20,
      film: 15,
      tedx: 25,
      ted: 20,
      alumni: 20,
      nss: 20,
      nirmaan: 25,
      sovesa: 25,
      gurukul: 20,
      bitsmun: 25,
      toastmasters: 25,
      'public policy': 25,
      consulting: 20,
      finance: 15,
      quant: 20,
      product: 15,
      regional: 20,
      cultural: 20,
      'tech team': 20,
      robotics: 20,
      ieee: 25,
      acm: 25,
      asme: 25,
      ifsa: 25,
      robocon: 25,
      entrepreneurship: 20,
      innovation: 15,
      'wall street': 25,
      '180dc': 25,
      cel: 20,
      samiti: 20,
      mandal: 20,
      mandram: 20,
      vedike: 20,
      vihar: 15,
    },
  },
  {
    category: 'events',
    senderContains: [
      'oasis',
      'apogee',
      'cultural',
      'fest',
      'seminar',
      'workshop',
      'lecture',
      'colloquium',
      'symposium',
      'conference',
      'orientation',
      'embryo',
      'bits embryo',
    ],
    subjectWeights: {
      fest: 60,
      oasis: 80,
      apogee: 80,
      event: 40,
      'guest lecture': 70,
      seminar: 60,
      workshop: 50,
      webinar: 50,
      cultural: 45,
      techno: 40,
      'management fest': 60,
      concert: 50,
      nukkad: 60,
      'pro night': 60,
      exhibition: 40,
      showcase: 35,
      'institute day': 60,
      'annual day': 55,
      techfest: 70,
      'tech fest': 70,
      meeting: 65,
      talk: 55,
      'talk by': 65,
      'fireside chat': 60,
      panel: 50,
      'panel discussion': 60,
      summit: 55,
      conference: 55,
      colloquium: 55,
      'invited talk': 70,
      'public lecture': 65,
      'distinguished lecture': 75,
      'department talk': 65,
      'tech talk': 65,
      'industry talk': 65,
      'alumni talk': 60,
      inauguration: 55,
      valedictory: 55,
      keynote: 55,
      plenary: 50,
      meetup: 50,
      roundtable: 50,
      'open house': 50,
      'demo day': 55,
      'seminar series': 65,
      'talk series': 65,
      'lecture series': 65,
      'training session': 50,
      'orientation session': 55,
      orientation: 55,
      'information session': 50,
      'town hall': 60,
      convocation: 60,
      'community meeting': 60,
      'department meeting': 55,
      'faculty meeting': 55,
      'committee meeting': 55,
      'board meeting': 55,
      'council meeting': 55,
      agenda: 55,
      discussion: 50,
      session: 50,
      viva: 55,
      schedule: 50,
      'calendar invite': 60,
      'you are invited': 65,
      presentation: 50,
      'google meet': 60,
      'zoom meeting': 60,
      'teams meeting': 60,
      'join us': 55,
      'please attend': 55,
      'ai talk': 65,
      'ai seminar': 60,
      'machine learning talk': 60,
      'campus event': 55,
      embryo: 60,
    },
    snippetWeights: {
      fest: 30,
      event: 25,
      register: 20,
      workshop: 25,
      seminar: 25,
      meeting: 35,
      talk: 30,
      lecture: 30,
      panel: 20,
      summit: 20,
      conference: 25,
      speaker: 20,
      presentation: 25,
      invite: 20,
      rsvp: 20,
      attend: 20,
      keynote: 20,
      auditorium: 20,
      venue: 20,
      'google meet': 35,
      zoom: 30,
      teams: 30,
      agenda: 25,
      hall: 15,
      date: 15,
      time: 15,
      calendar: 20,
      invited: 20,
      session: 20,
      orientation: 20,
    },
  },
  {
    category: 'augsd',
    senderExact: [
      'augsd',
    ],
    senderContains: [
      'augsd@',
      'augsd.bits-pilani',
    ],
    subjectWeights: {
      'ps-i': 50,
      'ps-1': 50,
      'ps-ii': 50,
      'ps-2': 50,
      'ps-i feedback': 70,
      'ps-1 feedback': 70,
      'semester registration': 60,
      'course registration': 60,
      'add/drop': 50,
      'grade sheet': 60,
      transcript: 60,
    },
  },
  {
    category: 'academics',
    senderContains: [
      'faculty',
      'professor',
      'dr.',
      'instructor',
      'hod',
      'department',
    ],
    subjectWeights: {
      exam: 60,
      'mid-sem': 70,
      compre: 70,
      'end-sem': 65,
      assignment: 55,
      tutorial: 50,
      lecture: 45,
      class: 35,
      timetable: 60,
      'academic calendar': 65,
      marks: 55,
      grading: 50,
      quiz: 50,
      test: 40,
      sessional: 55,
      'project submission': 60,
      lab: 40,
      practical: 40,
      course: 35,
      syllabus: 55,
      curriculum: 55,
      presentation: 30,
      viva: 60,
      attendance: 50,
      bonus: 40,
      regulation: 45,
      ordinance: 50,
      huel: 75,
      huelp: 75,
      opel: 75,
      cdc: 60,
      erp: 50,
    },
    snippetWeights: {
      exam: 30,
      assignment: 25,
      lecture: 25,
      submission: 20,
      ' marks': 20,
      faculty: 20,
      course: 15,
    },
  },
  {
    category: 'administration',
    senderContains: [
      'infrastructure',
      'installation',
      'hostel',
      'warden',
      'mess',
    ],
    subjectWeights: {
      campus: 50,
      bench: 40,
      installation: 55,
      infrastructure: 60,
      maintenance: 50,
      facility: 50,
      'office order': 65,
      administrative: 55,
      hostel: 65,
      warden: 70,
      mess: 60,
      room: 35,
      accommodation: 50,
      allotment: 55,
      dining: 45,
      food: 30,
      catering: 50,
      complaint: 35,
      'hostel fee': 55,
      'hostel allotment': 65,
      vacating: 50,
      checkout: 45,
    },
    snippetWeights: {
      campus: 25,
      installation: 30,
      infrastructure: 30,
      hostel: 30,
      warden: 35,
      mess: 25,
      room: 20,
      allotment: 30,
    },
  },
  {
    category: 'admin',
    senderExact: [
      'registrar',
      'dean',
      'director',
      'principal',
      'controller of examination',
      'office of the registrar',
      'office of the dean',
      'bits admin',
      'mail admin',
      'mail administrator',
      'chief warden',
      'associate dean',
    ],
    senderContains: [
      'registrar@',
      'dean@',
      'director@',
      'admin@bits-pilani',
      'mailadmin@',
      'mail-admin@',
      'chief warden@',
      'associate.dean@',
    ],
    subjectWeights: {
      circular: 70,
      'official notice': 75,
      notification: 50,
      policy: 55,
      ordinance: 60,
      regulation: 50,
      holiday: 50,
      'institute holiday': 65,
      'institute closure': 65,
      'holiday list': 60,
      'important notice': 55,
      mandatory: 45,
      convocation: 60,
      'fee deadline': 55,
      'fee payment': 55,
      'tuition fee': 55,
      'anti-ragging': 60,
      disciplinary: 55,
    },
    snippetWeights: {
      circular: 35,
      notice: 20,
      mandatory: 25,
      holiday: 25,
      policy: 25,
    },
  },
  {
    category: 'ps',
    senderExact: [
      'ps-i',
      'ps-i cell',
      'ps division',
      'ps department',
      'ps office',
      'ps feedback',
    ],
    senderContains: [
      'psadmin',
      'ps cell',
      'practice school',
      'psdivision',
      'psd',
      'im.psd',
      'instruction & monitoring',
      'instruction and monitoring',
    ],
    subjectWeights: {
      'ps-i': 80,
      ps1: 75,
      'ps-ii': 80,
      ps2: 75,
      'practice school': 85,
      'ps allotment': 80,
      'ps feedback': 85,
      'ps station': 75,
      'ps project': 70,
      'ps report': 70,
      'ps presentation': 70,
      'ps evaluation': 75,
      'ps guide': 65,
      'ps mentor': 65,
      'ps internship': 70,
      'industry practice': 60,
      'ps-i feedback': 90,
      'ps-ii feedback': 90,
      'ps grades': 80,
      'ps grading': 80,
      psms: 85,
      'practice school management system': 80,
      'final report': 65,
      'end semester report': 75,
      'faculty in charge': 70,
      fic: 55,
      mentor: 40,
      'organization mentor': 65,
      'mid sem feedback': 70,
      station: 55,
    },
    snippetWeights: {
      'ps-i': 40,
      'ps-ii': 40,
      'practice school': 45,
      'ps feedback': 45,
      'ps station': 35,
      'ps project': 30,
      'ps report': 30,
      'ps guide': 30,
      feedback: 20,
      'industry training': 25,
    },
  },
  {
    category: 'library',
    senderContains: [
      'library',
      'circulation',
      'overdue',
      'lending',
      'book issue',
    ],
    subjectWeights: {
      library: 60,
      book: 40,
      'due date': 60,
      fine: 50,
      return: 30,
      borrow: 45,
      journal: 40,
      reference: 30,
      'digital library': 55,
      overdue: 55,
      renewal: 40,
      'book issue': 55,
      'book return': 55,
      circulation: 50,
      'book due': 55,
      'late fine': 55,
    },
    snippetWeights: {
      library: 25,
      book: 20,
      due: 30,
      fine: 30,
      overdue: 30,
      circulation: 25,
      borrow: 20,
      return: 15,
    },
  },
  {
    category: 'technology',
    senderExact: [
      'nvidia',
      'openai',
      'anthropic',
      'google ai',
      'deepmind',
      'meta ai',
      'hugging face',
      'kaggle',
      'github',
      'gitlab',
      'vercel',
      'netlify',
      'docker',
      'kubernetes',
      'aws',
      'azure',
      'gcp',
      'arxiv',
      'papers with code',
      'towards data science',
      'medium',
      'substack',
      'dev.to',
      'cursor',
      'supabase',
      'cloudflare',
      'replit',
      'openrouter',
      'base44',
    ],
    subjectWeights: {
      newsletter: 45,
      digest: 45,
      'weekly digest': 55,
      'what\'s new': 40,
      'release notes': 50,
      'new feature': 45,
      'product update': 50,
      developer: 35,
      'dev update': 50,
      'machine learning': 35,
      llm: 35,
      tutorial: 30,
      'getting started': 30,
      'blog post': 35,
      version: 30,
      changelog: 45,
      claude: 50,
      gpt: 45,
      gemini: 35,
      'open source': 35,
      'open-source': 35,
      cursor: 55,
      supabase: 55,
      cloudflare: 55,
      replit: 55,
    },
    snippetWeights: {
      newsletter: 25,
      release: 20,
      feature: 15,
      tutorial: 15,
    },
  },
  {
    category: 'spam',
    senderExact: [
      'noreply',
      'no-reply',
      'do-not-reply',
      'donotreply',
    ],
    senderContains: [
      'marketing',
      'promo',
      'ad-',
      'ads.',
      'sponsored',
      'newsletter',
      'bulk',
    ],
    subjectWeights: {
      unsubscribe: 60,
      'opt out': 55,
      discount: 50,
      offer: 40,
      'limited time': 50,
      'buy now': 60,
      free: 30,
      deal: 40,
      promotion: 50,
      advertisement: 55,
      'click here': 50,
      subscribe: 40,
      winner: 60,
      congratulations: 40,
      'you won': 65,
      claim: 45,
      prize: 45,
      reward: 40,
      'exclusive deal': 55,
      'flash sale': 55,
      'black friday': 50,
      'cyber monday': 50,
      'act now': 50,
      hurry: 40,
      'amazing offer': 55,
      'special offer': 50,
      newsletter: 45,
      marketing: 50,
      promo: 45,
      'bulk mail': 55,
      'mailing list': 45,
      'weekly digest': 40,
      'daily digest': 40,
    },
    snippetWeights: {
      unsubscribe: 35,
      marketing: 30,
      promotion: 25,
      offer: 20,
      discount: 25,
      buy: 20,
      newsletter: 25,
      'bulk mail': 25,
      'mailing list': 20,
    },
  },
];
